#!/bin/sh

set -e

chmod +x $0

case $1 in
     --help)
        ./abi-compliance-checker.pl --help 2>&1 | sed -e '/^Report/ p' -e '/Examples:/,/^Report/ d' -e '/Name:/,/^$/ d' -e 's,./abi-compliance-checker.pl,abi-compliance-checker,' -e '/Usage:/ d'
        ;;
    --version)
        dpkg-parsechangelog | sed -r -e '3,$ d' -e 's/^[a-zA-Z]*: //' -e '2 s/^/ /' | tr -d '\n' ; echo
        ;;
    --help2man)
        help2man -n "$(sed -e '/Description:/ !d' -e 's/Description: //' debian/control)" -N $0 | sed 's/.SH "REPORTING BUGS"/.SH "EXAMPLES"\nYou can see example usage and example descriptors in the \\-\\-help output.\n.SH "REPORTING BUGS"/'
        ;;
    --man)
        bash $0 --manbash
        ;;
    --manbash)
        eval "man <($0 --help2man)" # a hack because of the bashism
        ;;
esac

